### ISSUE TITLE
branch: undefined

### ISSUE THREAD

**Issue by chonigman** [onsails/cloudbuild-slack#74]
Hi! First of all thanks for this easy to use script  to setup slack notifications. I tried the GCP tutorial and it was a bit absurd. So I've deployed the cloud function but when I get the message in slack it says **branch**:undefined.  When looking at the logs I see a printout that states the branch name but not sure how to fix this. 

I did need to deploy to a nodejs12 runtime as I was getting errors trying to create the nodejs10 runtime. 

Thanks!

**Comment by onsails** [comment]
Are you sure you are deploying function from this exact repo, not the GCP tutorial? 
This function is different from the one is used by GCP tutorial and for sure this function does not produce messages like the one in the screenshot. Please make sure you deploy using `deploy.sh` form this repo.

**Comment by chonigman** [comment]
Yes I am sure. I've deleted everything I made for that tutorial. I also deleted the cloud function created by the deploy script and all related artifacts and then re-run the deploy script. I still get the same formatting on messages. I can also confirm that the cloud function is triggering. 

The cloud build itself is setup to trigger by pushing to my bitbucket repo. Is there a possibility that this integration causes the issue? Or could it be that I changed the node environment to 12 as I previously stated. 

Functionally, nothing seems wrong but I just want to be able to display what branch was built. 

Thanks for your help.

**Comment by onsails** [comment]
Are you able to share function logs?

**Comment by chonigman** [comment]
Sure. I couldn't figure out a better way to grab them (the only other option was json which looked a mess). 

![log_1](https://user-images.githubusercontent.com/1154580/118022419-3500e880-b311-11eb-890e-b41f4802da46.png)
![log_2](https://user-images.githubusercontent.com/1154580/118022446-3a5e3300-b311-11eb-9733-1541a5cb7c12.png)
![log_3](https://user-images.githubusercontent.com/1154580/118022452-3cc08d00-b311-11eb-9b3e-493ec825efd4.png)

**Comment by onsails** [comment]
please try fix-branch-name branch

**Comment by chonigman** [comment]
Hi @onsails. Thanks for your assistance. This did not work for me. It says that `build.BRANCH_NAME` does not exist. Perhaps this is a fault of my cloud run/build set up. I do set the BRANCH_NAME explicitly in my variable section of the cloud build trigger. I noticed that the 'substitutions' object had the values I needed so I changed the line of code in render.ts to 

text: `*Repo*: ${repoSource.repoName}, *branch*: ${build.substitutions['BRANCH_NAME']}, *commit*: ${build.substitutions['SHORT_SHA']}\n<${build.logUrl}|*Details*>\`

Which seems to work for me now. Happy to help debug if it helps you. Appreciate your help and this repo, it's a nice addition to my ci pipeline.

**Comment by onsails** [comment]
Ah, that's it. It's in substitution. I've updated fix-branch-name branch.

As for message customisation you can also set 

```yaml
substitutions:
  _SLACK_MESSAGE_TEMPLATE: '<%= emoji %> *https://<%= build.substitutions._OVERLAY %>.example.com* frontend build & deploy `<%= build.id %>` <%= build.status %>'
``` 

to receive completely custom message like the one in readme.

**Comment by chonigman** [comment]
Perfect. Yeah I was able to set the custom template now as well. Thanks again!

**Comment by onsails** [comment]
could you please test if the new fix-branch-name branch works?

**Comment by chonigman** [comment]
Confirmed this is working! Thank you. 🙏
